[package]
name = "sonar-app"
description = "Sonar's search window and tray icon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
anyhow.workspace = true
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
sonar-core.workspace = true
tauri.workspace = true
tauri-plugin-opener.workspace = true
tauri-plugin-single-instance.workspace = true
tauri-plugin-updater.workspace = true

[target.'cfg(not(target_os = "linux"))'.dependencies]
tauri-plugin-global-shortcut.workspace = true

[target."cfg(windows)".dependencies]
windows-registry.workspace = true
